name: CD Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t tarea1:${{ github.sha }} .
          docker tag tarea1:${{ github.sha}} ${{ secrets.ECR_REPOSITORY_URI}}:latest

      # Step 3: Push Docker Image to ECR
      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Push image to Amazon ECR
      - name: Push to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          REPOSITORY_URI=${{ secrets.ECR_REPOSITORY_URI }}
          docker push REPOSITORY_URI:latest
          docker push REPOSITORY_URI:IMAGE_TAG
#        env:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}

#      # Step 4: Deploy to AWS ECS
#      - name: Deploy to AWS ECS
#        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#        with:
#          task-definition: ecs-task-def.json
#          service: my-ecs-service
#          cluster: my-cluster
#          wait-for-service-stability: true
          
          
