name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t tarea1:${{ github.sha }} .
          docker tag tarea1:${{ github.sha}} ${{ secrets.ECR_REPOSITORY_URI}}/tarea1:latest

      # Step 3: Push Docker Image to ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to ECR
        run: |
          docker tag my-image:${{ github.sha }} ${{ secrets.AWS_ECR_URI }}/my-image:${{ github.sha }}
          docker push ${{ secrets.AWS_ECR_URI }}/my-image:${{ github.sha }}

      # Step 4: Deploy to AWS ECS
      - name: Deploy to AWS ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: my-ecs-service
          cluster: my-cluster
          wait-for-service-stability: true